/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cassaproloco;

/**
 *
 * @author franc
 */
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.*;
import java.util.*;
import java.util.regex.*;
public class PannelloResocontoVendite extends JPanel {

    private JTable table;
    private DefaultTableModel model;
    private JComboBox<String> comboDate;
    private File csvFolder;
    private JLabel labelTotale;  

    public PannelloResocontoVendite(File csvFolder) {
        this.csvFolder = csvFolder;
        setLayout(new BorderLayout());

        model = new DefaultTableModel(new String[]{"Nome", "Quantità", "Incasso (€)"}, 0);
        table = new JTable(model);
        add(new JScrollPane(table), BorderLayout.CENTER);

        // Top panel: combo box date
        JPanel topPanel = new JPanel(new FlowLayout());
        comboDate = new JComboBox<>();
        caricaDateDisponibili();

        comboDate.addActionListener(e -> {
            String dataSelezionata = (String) comboDate.getSelectedItem();
            if (dataSelezionata != null) caricaVendite(dataSelezionata);
        });

        topPanel.add(new JLabel("Data:"));
        topPanel.add(comboDate);
        add(topPanel, BorderLayout.NORTH);

        // Bottom panel: totale
        JPanel bottomPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        labelTotale = new JLabel("Totale giornaliero: 0.00 €");
        bottomPanel.add(labelTotale);
        add(bottomPanel, BorderLayout.SOUTH);
    }

    /** Popola la combo box con le date trovate nei nomi dei file CSV */
    private void caricaDateDisponibili() {
        File[] files = csvFolder.listFiles((dir, name) -> name.matches("report_\\d{4}-\\d{2}-\\d{2}\\.csv"));
        if (files == null) return;

        ArrayList<String> dateList = new ArrayList<>();
        Pattern pattern = Pattern.compile("report_(\\d{4}-\\d{2}-\\d{2})\\.csv");

        for (File f : files) {
            Matcher m = pattern.matcher(f.getName());
            if (m.matches()) {
                dateList.add(m.group(1));
            }
        }

        Collections.sort(dateList);
        comboDate.setModel(new DefaultComboBoxModel<>(dateList.toArray(new String[0])));
    }

    /** Carica e somma le vendite dal file CSV per la data selezionata */
    private void caricaVendite(String data) {
        model.setRowCount(0);
        File file = new File(csvFolder, "report_" + data + ".csv");

        if (!file.exists()) {
            JOptionPane.showMessageDialog(this, "File non trovato:\n" + file.getName());
            labelTotale.setText("Totale giornaliero: 0.00 €");
            return;
        }

        Map<String, int[]> vendite = new HashMap<>();
        int totaleCentesimi = 0;

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String riga;
            boolean firstLine = true;
            while ((riga = br.readLine()) != null) {
                if (firstLine) {
                    firstLine = false;
                    continue;
                }

                String[] campi = riga.split(",");
                if (campi.length < 4) continue;

                String nome = campi[1].trim();
                int quantita = Integer.parseInt(campi[2].trim());
                double prezzo = Double.parseDouble(campi[3].trim());

                int incassoCentesimi = (int)(prezzo * quantita * 100);
                totaleCentesimi += incassoCentesimi;

                vendite.putIfAbsent(nome, new int[]{0, 0});
                vendite.get(nome)[0] += quantita;
                vendite.get(nome)[1] += incassoCentesimi;
            }

            // Popola la tabella
            for (Map.Entry<String, int[]> entry : vendite.entrySet()) {
                String nome = entry.getKey();
                int qty = entry.getValue()[0];
                double incasso = entry.getValue()[1] / 100.0;
                model.addRow(new Object[]{nome, qty, String.format("%.2f", incasso)});
            }

            labelTotale.setText(String.format("Totale giornaliero: %.2f €", totaleCentesimi / 100.0));

        } catch (IOException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Errore durante la lettura:\n" + e.getMessage());
            labelTotale.setText("Totale giornaliero: 0.00 €");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
